"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import urlparse

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# override=True: sin esto, python-dotenv no pisa una variable que ya este
# en el entorno del proceso. Con el autoreload de "runserver" (que reexec'ea
# el proceso pero le hereda el mismo os.environ, no uno nuevo del shell), un
# .env editado mientras el server seguia corriendo se quedaba sin aplicar
# nunca -> caso real: MQTT_USERNAME quedo pegado al valor viejo (sin permiso
# de Publish) varios reinicios despues de haberlo corregido en el archivo.
load_dotenv(BASE_DIR / ".env", override=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "")
if not SECRET_KEY:
    raise RuntimeError(
        "DJANGO_SECRET_KEY no esta definida. Copia .env.example a .env y completa los valores."
    )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "True") == "True"

ALLOWED_HOSTS = [
    h.strip() for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",") if h.strip()
]


# Application definition

INSTALLED_APPS = [
    # jazzmin debe ir antes de django.contrib.admin (reemplaza sus templates
    # por los suyos) - ver JAZZMIN_SETTINGS/JAZZMIN_UI_TWEAKS mas abajo.
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'home',
    'historico',
    'tiemporeal',
    'configuracion',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases
# Misma base PostgreSQL (Render) que usa backend/telemetry-worker.py, para
# que el dashboard lea los datos que ese worker ya esta guardando.

DATABASE_URL = os.environ.get("DATABASE_URL", "")
if not DATABASE_URL:
    raise RuntimeError(
        "DATABASE_URL no esta definida. Copia .env.example a .env y completa los valores."
    )

# MQTT (broker HiveMQ, ver backend/.env.example para la plantilla completa).
# El dashboard solo PUBLICA retained a traves de la vista de Configuracion
# (ver configuracion/mqtt_publish.py, topic config/<node_id> documentado en
# Documentation/README.md); nunca se suscribe ni mueve credenciales al
# navegador.
MQTT_HOST = os.environ.get("MQTT_HOST", "")
MQTT_PORT = int(os.environ.get("MQTT_PORT", "8883"))
MQTT_USERNAME = os.environ.get("MQTT_USERNAME", "")
MQTT_PASSWORD = os.environ.get("MQTT_PASSWORD", "")
MQTT_CLIENT_ID = os.environ.get("MQTT_CLIENT_ID", "dashboard_config_publisher")

_db_url = urlparse(DATABASE_URL)

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': _db_url.path.lstrip('/'),
        'USER': _db_url.username,
        'PASSWORD': _db_url.password,
        'HOST': _db_url.hostname,
        'PORT': _db_url.port or 5432,
        'OPTIONS': {'sslmode': 'require'},
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Guatemala'

USE_I18N = True

# node_readings.reading_time (y las demas columnas de hora de esta misma
# base) son TIMESTAMP *sin* zona horaria con la hora local de Guatemala ya
# calculada - ver el comentario de GUATEMALA_TZ en backend/telemetry-worker.py.
# Con USE_TZ=True Django asumiria que esos valores naive estan en UTC y los
# recorreria mal; en False los toma tal cual, igual que el resto del backend.
USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}


# django-jazzmin (personalizacion visual de /admin/)
# https://django-jazzmin.readthedocs.io/
# site_logo/site_icon reutilizan el isotipo oficial del proyecto (el mismo
# archivo que existe para la marca, ver static/assets/images/isotipo.svg;
# el sidebar del dashboard en si usa un SVG inline, no este archivo, pero
# es el isotipo "fuente" del proyecto). Rutas relativas a STATICFILES_DIRS.
JAZZMIN_SETTINGS = {
    "site_title": "IoT Admin",
    "site_header": "IoT Admin",
    "site_brand": "IoT Admin",
    "site_logo": "assets/images/isotipo.svg",
    "site_icon": "assets/images/isotipo.svg",
    "login_logo": "assets/images/isotipo.svg",
    "site_logo_classes": "",
    "welcome_sign": "Panel de administracion - IoT Admin",
    "copyright": "IoT Admin",
    "show_ui_builder": False,
    # Fuerza el verde institucional en la barra superior (ver
    # static/assets/css/jazzmin-custom.css para el porque hace falta esto
    # ademas de JAZZMIN_UI_TWEAKS["navbar"]).
    "custom_css": "assets/css/jazzmin-custom.css",
    # Boton visible en la barra superior (no escondido en un dropdown)
    # para volver al dashboard publico del proyecto. "url": "home" se
    # resuelve via reverse() porque no tiene "/" (ver get_custom_url() en
    # jazzmin/utils.py).
    "topmenu_links": [
        {"name": "Volver al Dashboard", "url": "home", "icon": "fas fa-arrow-left"},
    ],
    # "Cerrar sesion" ya existe por defecto dentro del dropdown del
    # usuario (arriba a la derecha), pero como boton escondido ahi es
    # facil de pasar por alto. custom_js agrega uno visible en la barra
    # superior que simplemente envia el formulario de logout real que
    # jazzmin ya genera (#logout-form, con su propio CSRF) - ver
    # static/assets/js/jazzmin-custom.js.
    "custom_js": "assets/js/jazzmin-custom.js",
}

# Tema verde (acorde al verde institucional del dashboard, ver
# --brand-forest-dark/--brand-lime en static/assets/css/main.css):
# "minty" es el Bootswatch verde/menta que trae jazzmin de fabrica.
#
# OJO: django-jazzmin 3.0.5 reescribio su theming sobre AdminLTE 4 +
# Bootstrap 5 (ver el comentario "AdminLTE v4 / Bootstrap 5" en su propio
# jazzmin/css/main.css), y varias de las clases "skin" que documentan sus
# defaults (sidebar-dark-<color>, navbar-<color>, accent-<color>, nav-flat)
# ya NO tienen ningun CSS real detras en esta version - se confirmo
# revisando el paquete instalado (ni en jazzmin/css/main.css ni en
# vendor/adminlte/css/adminlte.min.css aparece, por ejemplo,
# ".sidebar-dark-success" ni ".navbar-success"). Usarlas no rompe nada por
# si solas, pero "navbar": "navbar-dark" SI es una clase real de Bootstrap
# (fuerza texto claro) y, sin un bg-* real que la acompañe, quedaba sobre
# el "bg-body" claro del template -> texto blanco sobre fondo blanco,
# haciendo que la barra superior completa (y los botones de topmenu_links/
# custom_js de abajo, que viven ahi) se viera vacia. Por eso aqui se le
# agrega "bg-success" explicito en vez de confiar en una clase "skin".
JAZZMIN_UI_TWEAKS = {
    "theme": "minty",
    "default_theme_mode": "light",
    "navbar": "navbar-dark bg-success",
    "button_classes": {
        "primary": "btn-success",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}
